### ISSUE TITLE
W7 64 bit crash

### ISSUE THREAD

**Issue by astrobeed** [officinerobotiche/simple_unav_console#1]
Windows 7 64 bit sp1, as soon as you open the serial communication program crashes.

**Comment by Myzhar** [comment]
@rbonghi I noticed the same problem. I think it is related to somthing strange that happens in orblibcpp during connection.
We must indagate deeply...

**Comment by katodo** [comment]
I've found same problem last night n Ubuntu 14.04 @64bit...

**Comment by Myzhar** [comment]
@astrobeed, @katodo 
Did you test it with or without a board connected?

**Comment by rbonghi** [comment]
Solved https://github.com/officinerobotiche/orblibcpp/commit/c51180cb90db4d1edd026b1e75bc42a60b1bf85e :+1:
